### PR TITLE
Force turn

### PR DESCRIPTION
**Pull request by xdumaine**
Similar to `useFirefoxFakeDevice` in getUserMedia.js, this is a localStorage key to force candidates to filter out all non-relay candidates, in order to test TURN server configuration. I've been using this in my project and wanted to suggest it for use in the main project. Thoughts @fippo @legastero?

### CODE REVIEW

**Comment by fippo** [comment]
hrm... i'd check for the value of iceTransports in the peerconnection config instead. Also, you only need to do that in Firefox since recent chrome versions already do the heavy lifting for you when you set that to 'relay' (see e.g. the candidate gathering demo in the webrtc samples repo)

**Comment by xdumaine** [comment]
Aha, I forgot about that `iceTransports` option. Will update soon...

**Comment by xdumaine** [comment]
@fippo Could you clarify what it means for the localCandidateType to be relay while the remote may be stun? I guess I thought if TURN is used, they'd both be relay. To clarify, this is the case where one user has `iceTransports` set to `relay` and the other doesn't specify.

**Comment by fippo** [comment]
@xdumaine that can happen. It means that one user is connected to the other's relayed candidate. Which, on the same TURN server, is almost equivalent to having to using relay, but the relay-relay candidate pair gets a slightly lower priority due to ice rules

**Comment by fippo** [comment]
+1 -- you should be able to npm publish now, i'd consider that a patch since it works around a FF bug :-)

**Pull request merged**
